sudo: false
language: android
jdk:
  - oraclejdk8
install:
# Let's use the new command 'sdkmanager' to install Android SDK components
- yes | sdkmanager --verbose "build-tools;26.0.2"
- yes | sdkmanager --verbose "platform-tools"
- yes | sdkmanager --verbose "tools"
- yes | sdkmanager --verbose "platforms;android-26"
- yes | sdkmanager --verbose "system-images;android-24;default;armeabi-v7a"

# Check tools and dependencies installed
- yes | sdkmanager --list
script:
- ./gradlew clean build